#!/usr/bin/env node
// scripts/generateSubdivisionNotes.js
// Generates full-length "Geography of <subdivision>, <country>" preset notes
// with Gemini Pro and writes them to:
//   data/countryGeoNotes/subdivisionNotesGenerated.json  (resume state)
//   data/countryGeoNotes/subdivisionNotesGenerated.js    (module imported by subdivisions.js)
//
// Usage:  node scripts/generateSubdivisionNotes.js [--model=<gemini model id>]
// Resume: already-generated slugs are skipped, so re-run after a partial failure.
// Each note records the model that generated it in its "model" field.

import dotenv from 'dotenv';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { SUBDIVISION_GROUPS } from '../data/countryGeoNotes/subdivisions.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);
const ROOT       = join(__dirname, '..');

dotenv.config({ path: join(ROOT, '.env') });

const GEMINI_PRO = 'gemini-3.1-pro-preview'; // must match server.js GEMINI_PRO
const MODEL_ID   = process.argv.find(a => a.startsWith('--model='))?.slice('--model='.length) || GEMINI_PRO;
const JSON_PATH  = join(ROOT, 'data', 'countryGeoNotes', 'subdivisionNotesGenerated.json');
const JS_PATH    = join(ROOT, 'data', 'countryGeoNotes', 'subdivisionNotesGenerated.js');
const CONCURRENCY = 8;

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');
const model = genAI.getGenerativeModel({
  model: MODEL_ID,
  generationConfig: { responseMimeType: 'application/json', temperature: 0.4 },
});

const slugify = value => String(value)
  .normalize('NFKD')
  .replace(/[̀-ͯ]/g, '')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '');

function parseAIJson(text) {
  if (!text || typeof text !== 'string') return null;
  const trimmed = text.trim();
  try { return JSON.parse(trimmed); } catch {}
  const defenced = trimmed
    .replace(/^```(?:json)?\s*\n?/i, '').replace(/\n?```\s*$/i, '')
    .trim();
  try { return JSON.parse(defenced); } catch {}
  return null;
}

function buildPrompt({ name, capital, type, country }) {
  return `You are writing a preset study note for a geography study app used by students preparing for map quizzes and quiz bowl. Write about ${name}, a first-level ${type.toLowerCase()} of ${country}. Its administrative center is ${capital}.

Return strict JSON with exactly these keys:
{
  "cues": [six to eight short Cornell-style recall questions about ${name}],
  "mainNotes": "markdown string",
  "summary": "two to three sentence plain-text summary"
}

Requirements for mainNotes:
- 450 to 650 words of factual content in markdown.
- Use exactly these H2 sections in this order: "## Location within ${country}", "## Physical features", "## Climate", "## Economy & cities", "## History & culture", "## Quick facts".
- "## Quick facts" is a bullet list: country, subdivision type, administrative center, approximate area, approximate population, largest city if different from the administrative center, and one or two signature features.
- Name real neighboring subdivisions, real rivers, mountains, coastlines, parks, industries, and cities. Prefer well-established facts; use "about" or "roughly" for figures.
- Plain, factual, encyclopedic tone. No hype words, no rhetorical questions, no em dashes (use commas or periods instead), no second person.
- If the subdivision's political status is disputed or sensitive (for example Taiwan, Jammu and Kashmir, Crimea-adjacent regions), state the situation neutrally in one sentence within the Location section.
- Do not include a title heading; the app supplies the title "Geography of ${name}, ${country}".

Requirements for cues: recall questions a student answers from the note, such as the administrative center, distinctive landforms, borders, and economy.

Requirements for summary: two to three sentences a student could read as a quick refresher. No markdown.`;
}

function isUsable(note) {
  return note
    && Array.isArray(note.cues) && note.cues.length >= 5
    && note.cues.every(c => typeof c === 'string' && c.trim())
    && typeof note.mainNotes === 'string' && note.mainNotes.length > 1200
    && note.mainNotes.includes('## Quick facts')
    && typeof note.summary === 'string' && note.summary.trim().length > 80;
}

function loadState() {
  if (!existsSync(JSON_PATH)) return {};
  try { return JSON.parse(readFileSync(JSON_PATH, 'utf8')); } catch { return {}; }
}

function saveState(state) {
  writeFileSync(JSON_PATH, JSON.stringify(state, null, 2));
  const body = [
    '// AUTO-GENERATED by scripts/generateSubdivisionNotes.js. Do not edit by hand;',
    '// re-run the script instead. Each note records its generating model in "model".',
    `export const GENERATED_SUBDIVISION_NOTES = ${JSON.stringify(state, null, 2)};`,
    '',
  ].join('\n');
  writeFileSync(JS_PATH, body);
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function generateOne(item) {
  const prompt = buildPrompt(item);
  const delays = [2000, 8000, 20000];
  for (let attempt = 0; attempt <= delays.length; attempt++) {
    try {
      const result = await model.generateContent(prompt);
      const note = parseAIJson(result.response.text());
      if (isUsable(note)) {
        return {
          cues: note.cues.map(c => String(c).trim()).slice(0, 8),
          mainNotes: String(note.mainNotes).trim(),
          summary: String(note.summary).trim(),
          model: MODEL_ID,
        };
      }
      throw new Error('response failed validation');
    } catch (err) {
      const msg = err?.message || String(err);
      if (attempt === delays.length) throw new Error(msg);
      console.warn(`  retry ${attempt + 1} for ${item.name}, ${item.country}: ${msg.slice(0, 140)}`);
      await sleep(delays[attempt]);
    }
  }
}

async function main() {
  const queue = SUBDIVISION_GROUPS.flatMap(group =>
    group.rows.map(row => ({
      ...row,
      country: group.country,
      slug: `subdivision-${slugify(group.country)}-${slugify(row.name)}`,
    }))
  );
  const state = loadState();
  const pending = queue.filter(item => !state[item.slug]);
  console.log(`${queue.length} subdivisions total, ${queue.length - pending.length} already generated, ${pending.length} to go.`);
  if (!pending.length) { saveState(state); return; }

  let done = 0, failed = 0, cursor = 0;
  async function worker() {
    while (cursor < pending.length) {
      const item = pending[cursor++];
      try {
        state[item.slug] = await generateOne(item);
        done++;
        saveState(state);
        console.log(`[${done + failed}/${pending.length}] ok  ${item.name}, ${item.country}`);
      } catch (err) {
        failed++;
        console.error(`[${done + failed}/${pending.length}] FAIL ${item.name}, ${item.country}: ${err.message.slice(0, 160)}`);
      }
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  saveState(state);
  console.log(`Done. ${done} generated, ${failed} failed. Re-run the script to retry failures.`);
  if (failed) process.exitCode = 1;
}

main().catch(err => { console.error(err); process.exit(1); });
